#ifndef RESOURCES_H
#define RESOURCES_H

#include <windows.h>

// Icon resource IDs
#define IDI_APPICON 100

#define IDD_UPDATE_PROMPT 101
#define IDD_DOWNLOAD_SIZE_ERROR 102
#define IDC_UPDATE_MESSAGE 1002
#define IDC_UPDATE_NOTES 1003
#define IDC_DOWNLOAD_SIZE_MESSAGE 1004
#define IDC_DOWNLOAD_SIZE_OPEN_RELEASE 1005

#endif // RESOURCES_H
