#ifndef TRAY_SESSION_FINISHED_ACTION_H
#define TRAY_SESSION_FINISHED_ACTION_H

typedef enum {
    SESSION_FINISHED_NONE = 0,
    SESSION_FINISHED_SHUTDOWN,
    SESSION_FINISHED_SLEEP,
    SESSION_FINISHED_SHUTDOWN_GRACEFUL
} SessionFinishedAction;

#endif
